### ISSUE TITLE
Prev_post / next_post

### ISSUE THREAD

**Issue by novaugust** [novaugust/Novasper#12]
Casper made these so pretty.

**Comment by tsangiotis** [comment]
I am not very experienced with html/css situations but I've hacked stuff together so maybe I can give it a try. Could you briefly explain to me the workflow to get the needed changes from Casper without breaking what you have done?

**Comment by novaugust** [comment]
It's potentially as easy as just merging the master branch of Casper back
into the novasper branch of this repo. The headaches come when making sure
that weird things didn't get added on Casper that conflict with the
novasper customizations, and dealing with merge conflicts in general. I'm
travelling Europe currently, so probably won't try this myself for another
few weeks :) feel free to take a stab at it, or wait a bit knowing I'll get
on it sooner than later now that I know it's wanted
