### ISSUE TITLE
Support new navigation option

### ISSUE THREAD

**Issue by tsagi** [novaugust/Novasper#7]
As I see from the [5.9 release](https://github.com/TryGhost/Ghost/releases/tag/0.5.9) there is a new navigation helper. Any plan to support that?

**Comment by novaugust** [comment]
@tsagi Yep, it's in the works. Just need to find an evening to play with it - the navigation addition made some fundamental changes to the root html structure that need fixing, along with some quirky behaviour around the menu sliding in/out. I'll PR against this issue when I've got it fixed, hopefully within the week

**Comment by novaugust** [comment]
@tsagi The novasper branch has been updated to use ghost's new navigation code. Sadly, there's an animation bug on -webkit- that causes text to flicker when you hover over a post title. I'm going to fix that at some point in the future, then tag it and release. In the meanwhile, it *works*, it's just not perfect ;)

**Comment by tsangiotis** [comment]
Looks awesome!

**Comment by novaugust** [comment]
Released version 1.3.0
