### ISSUE TITLE
Full screen images on mobile have a gap on the right

### ISSUE THREAD

**Issue by tsagi** [novaugust/Novasper#9]
This is a full screen image.
![screenshot_2015-03-03-00-14-35](https://cloud.githubusercontent.com/assets/697354/6460084/f8086a3c-c19c-11e4-8c6f-152bf0c0d721.png)
As you see on the right there is a gap.

This image is not full screen on desktop but centered as it is of a smaller resolution but aligns left on mobile cutting some of the image's left doing so.
![screenshot_2015-03-03-00-14-42](https://cloud.githubusercontent.com/assets/697354/6460085/f98d18c6-c19c-11e4-954b-84922155ead6.png)

**Comment by novaugust** [comment]
@tsagi Thanks for the report! I had tested it on what I thought was mobile, not realizing the theme had another breakpoint at 500px ;) Fix en route

**Comment by novaugust** [comment]
Wow, you're going to want to wait for 1.3.1. Colors are goofed on 1.3.0
